"""One schema, three consumers (03b §4): the validator inside `write` (registry/config.py, registry/card.py), the
**typed model** and the **tool-call input schema** — both generated here from the same registry documents, so
"nothing to drift" is a test, not a hope (`tests/unit/test_codegen.py` regenerates and byte-compares).

What is generated: for each document type, a pydantic model whose scalar/table rows come from the schema document's
key rows (name, type, enum, pattern, range, required_when, default) and whose nested shapes are the discriminated
models of `registry/shapes.py` — the declared limit of the nine-member vocabulary, authored once and shared by the
three targets. From the model: the JSON Schema each tool call is constrained to, which is what makes "no freehand"
cheap rather than bureaucratic (round 57).

`model_dump(exclude_unset=True, by_alias=True)` is the one dump: the typed model is validated, never hashed, so
absent-vs-default survives into the raw value tree the hasher sees (W10, T6).
"""

from __future__ import annotations

import json
import keyword
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, Final

from ..core import canon
from .loader import Registry
from .vocabulary import SchemaDoc

GENERATED: Final = Path(__file__).parent / "generated"
HEADER: Final = '''"""GENERATED by isidium.store.registry.codegen — do not edit.

Source schemas: {sources}
Content address: {address}

The typed model (W10): validated, never hashed. `model_dump(exclude_unset=True, by_alias=True)` is the one dump —
absent stays absent, so the raw value tree the hasher sees is unchanged by typing.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import Field

from ..shapes import (
    Acceptance,
    Answer,
    BddNarrative,
    ClassicNarrative,
    EarsNarrative,
    Guidance,
    Hold,
    Question,
    Rule,
    SourceNarrative,
    SpikeNarrative,
    Strict,
    TaskNarrative,
)

Narrative = BddNarrative | EarsNarrative | ClassicNarrative | TaskNarrative | SpikeNarrative
'''

# The nested shapes a card head's table rows carry (the declared limit: `type = "table" | "array"` in card@1 says
# only that much, so the shape module names what it is).
CARD_FIELD_TYPES: Final[dict[str, str]] = {
    "narrative": "Narrative",
    "rules": "list[Rule]",
    "questions": "list[Question]",
    "answers": "list[Answer]",
    "guidance": "Guidance",
    "acceptance": "Acceptance",
    "hold": "Hold",
    "source_narrative": "SourceNarrative",
    "closures": "list[Any]",  # claims are appended by the store, never composed by a caller (1.7)
    "reopens": "list[Any]",
    "x": "dict[str, Any]",
    "depends_on": "list[Annotated[int, Field(ge=1)]]",
    "refs": "list[str]",
    "surfaces": "list[str]",
    "see": "list[str]",
    "tags": "list[str]",
}
# Names that would shadow a pydantic BaseModel attribute; pinned here, aliased like a keyword.
RESERVED: Final[frozenset[str]] = frozenset({"schema", "json", "dict", "copy", "fields", "construct", "validate"})
SCALARS: Final[dict[str, str]] = {
    "string": "str",
    "int": "int",
    "bool": "bool",
    "date": "str",
    "array": "list[Any]",
    "table": "dict[str, Any]",
}


def _py_type(row: Mapping[str, Any], overrides: Mapping[str, str]) -> str:
    name = str(row["name"])
    if name in overrides:
        return overrides[name]
    if "enum" in row:
        members = ", ".join(json.dumps(m) for m in row["enum"])
        return f"Literal[{members}]"
    return SCALARS.get(str(row.get("type")), "Any")


def _required(row: Mapping[str, Any]) -> bool:
    """Unconditionally required = `required_when = []` (an AND of no tests, L2-5). Conditionally required keys are
    Optional in the model and enforced by the profile — the tool surface must be able to compose a draft."""
    return row.get("required_when") == []


def _field_lines(rows: Sequence[Mapping[str, Any]], overrides: Mapping[str, str]) -> list[str]:
    """One line per key row. A key that is a Python keyword (`for`, `from`) or a pydantic attribute (`schema`) is
    emitted with a trailing underscore and its wire name as the alias; `model_dump(exclude_unset=True,
    by_alias=True)` is the one dump, so the raw value tree carries the schema's own key."""
    out: list[str] = []
    for row in rows:
        name = str(row["name"])
        t = _py_type(row, overrides)
        py = name + "_" if keyword.iskeyword(name) or name in RESERVED else name
        alias = f', alias="{name}"' if py != name else ""
        if _required(row):
            out.append(f"    {py}: {t}" + (f" = Field({alias[2:]})" if alias else ""))
        elif alias:
            out.append(f"    {py}: {t} | None = Field(default=None{alias})")
        else:
            out.append(f"    {py}: {t} | None = None")
    return out


def _model(class_name: str, doc: SchemaDoc, part: str, overrides: Mapping[str, str], doc_line: str) -> list[str]:
    rows = list(doc.get(part, []))
    lines = [f"class {class_name}(Strict):", f'    """{doc_line}"""', ""]
    lines += _field_lines(rows, overrides) or ["    pass"]
    lines.append("")
    lines.append("")
    return lines


def render_models(registry: Registry) -> str:
    card = registry.get("card@1")
    inbox = registry.get("inbox@1")
    sources = ", ".join(f"{d['name']}@{d['version']}" for d in (card, inbox))
    address = canon.content_address([card, inbox])
    body: list[str] = []
    body += _model(
        "CardHead",
        card,
        "head",
        CARD_FIELD_TYPES,
        "A card's typed head (03 §2.1). Conditionally required keys are Optional here; the profile (03 §3) decides.",
    )
    body += _model(
        "InboxRecord",
        inbox,
        "record",
        {"refs": "list[str]", "surfaces_touched": "list[str]", "from": "dict[str, Any]"},
        "One suggestion-inbox record (03a §2): intake or disposition; per-type presence is the record slot's.",
    )
    return HEADER.format(sources=sources, address=address) + "\n\n" + "\n".join(body).rstrip() + "\n"


# ---- the tool-call input schemas (the planner's surface) -----------------------------------------------------------


def tool_schemas(registry: Registry | None = None) -> dict[str, Any]:
    """The JSON Schema per tool the surface exposes: `write` and `ratify` carry the generated card head, so the model
    is constrained to the schema's form at the moment it writes; the rest are the verbs' typed arguments (1.2)."""
    from .generated import models

    head = models.CardHead.model_json_schema(ref_template="#/$defs/{model}")
    defs = head.pop("$defs", {})
    defs["CardHead"] = head  # the card head is itself a def: `write` and `ratify` reference it, never embed it twice
    card_doc: dict[str, Any] = {
        "type": "object",
        "additionalProperties": False,
        "required": ["head"],
        "properties": {
            "head": {"$ref": "#/$defs/CardHead"},
            "scope": {"type": "string", "description": "the `## Scope` section — the owner's words verbatim (T-B1)"},
            "updates": {
                "type": "array",
                "description": "append-only dated blocks (log class); the store stamps the header",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["title", "body"],
                    "properties": {"title": {"type": "string"}, "body": {"type": "string"}},
                },
            },
        },
    }
    defs["CardDocument"] = card_doc
    doc_ref = {"$ref": "#/$defs/CardDocument"}
    ids = {"type": "array", "items": {"type": "integer", "minimum": 1}, "minItems": 1}
    # One `$defs` root per tool, referenced twice rather than embedded twice: the card schema is ~20 KB, and a
    # planner session pays `tools/list` on every invocation (the round-42 lens; the review's E2).
    tools: dict[str, Any] = {
        "write": {
            "description": (
                "Write one governed document (03 §1.2): validate, compare-and-swap on the history head, derive the "
                "act from the diff, sign if the predicate says so, journal, write, commit. `new_slug` creates a card "
                "(the store allocates the id); otherwise `card` names an existing one and `base` is its head."
            ),
            "inputSchema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["document"],
                "properties": {
                    "card": {"type": "integer", "minimum": 1},
                    "new_slug": {"type": "string", "pattern": "^[a-z0-9][a-z0-9-]*$"},
                    "document": doc_ref,
                    "base": {
                        "type": "object",
                        "additionalProperties": False,
                        "required": ["seq", "h"],
                        "properties": {"seq": {"type": "integer"}, "h": {"type": "string"}},
                    },
                    "ref": {"type": "string", "description": "a judging ref `c<n>:sha256:<hex>` (5.2)"},
                },
            },
        },
        "ratify": {
            "description": (
                "The sitting (03 §1.12): a list of typed writes under ONE signature. `dry_run` runs the same function "
                "minus the signature and the writes and returns the verdicts — `{id: [{rule, path, detail}]}`, typed "
                "records keyed by card id, a `validate.failed` verdict carrying its own `verdicts` — and the exact "
                "display the signer shows."
            ),
            "inputSchema": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "ids": ids,
                    "writes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["document"],
                            "properties": {
                                "card": {"type": "integer", "minimum": 1},
                                "new_slug": {"type": "string", "pattern": "^[a-z0-9][a-z0-9-]*$"},
                                "document": {
                                    "type": "object",
                                    "description": (
                                        "the same shape as `write`'s document; the store validates it identically. "
                                        "Not re-embedded here: the card schema is ~20 KB and a planner session pays "
                                        "`tools/list` on every invocation — the constraint that matters is at `write`, "
                                        "where documents are authored (03b §4; the WP3 review's E2)."
                                    ),
                                },
                                "base": {
                                    "type": "object",
                                    "additionalProperties": False,
                                    "required": ["seq", "h"],
                                    "properties": {"seq": {"type": "integer"}, "h": {"type": "string"}},
                                },
                                "ref": {"type": "string"},
                            },
                        },
                    },
                    "dry_run": {"type": "boolean", "default": True},
                },
            },
        },
        "show": {
            "description": (
                "The one typed read (03 §1.2): a card, the board, the queue, the inbox or a registry schema."
            ),
            "inputSchema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["target"],
                "properties": {
                    "target": {"type": "string", "enum": ["card", "board", "queue", "inbox", "schema"]},
                    "id": {"type": "integer", "minimum": 1},
                    "name": {"type": "string", "pattern": "^[a-z][a-z0-9-]*@[1-9][0-9]*$"},
                },
            },
        },
        "check": {
            "description": (
                "Chain, recompute, signatures and bindings, the journal reconciliation, the whole-set rules."
            ),
            "inputSchema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["id"],
                "properties": {"id": {"type": "integer", "minimum": 1}},
            },
        },
        "suggest": {
            "description": (
                "Hand something noticed back to the tenant as a suggestion (03a): never a card, never guidance — the "
                "planner dispositions it with the owner."
            ),
            "inputSchema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["kind", "title", "body"],
                "properties": {
                    "kind": {
                        "type": "string",
                        "enum": ["card", "guidance", "debt", "docs", "test", "risk", "question"],
                    },
                    "title": {"type": "string", "maxLength": 120},
                    "body": {"type": "string", "maxLength": 2048},
                    "refs": {"type": "array", "items": {"type": "string"}},
                    "proposed_for": {"type": "integer", "minimum": 1},
                },
            },
        },
        "disposition": {
            "description": "Disposition one suggestion — with the owner, every time (round 28).",
            "inputSchema": {
                "type": "object",
                "additionalProperties": False,
                "required": ["suggestion", "outcome"],
                "properties": {
                    "suggestion": {"type": "string", "pattern": "^s[1-9][0-9]*$"},
                    "outcome": {"type": "string", "enum": ["accepted", "declined", "deferred"]},
                    "as": {"type": "string", "enum": ["card", "guidance", "note"]},
                    "reason": {"type": "string", "maxLength": 500},
                    "until": {"type": "string"},
                    "slug": {"type": "string", "pattern": "^[a-z0-9][a-z0-9-]*$"},
                },
            },
        },
    }
    tools["write"]["inputSchema"]["$defs"] = defs  # the one place the card schema is spelled out
    return tools


def render_tools(registry: Registry) -> str:
    return json.dumps(tool_schemas(registry), indent=2, sort_keys=True, ensure_ascii=False) + "\n"


# ---- write / verify --------------------------------------------------------------------------------------------


def generate(registry: Registry | None = None, out: Path | None = None) -> dict[Path, str]:
    """Render every generated artifact; returns {path: text} without writing (the drift test compares). The tool
    schemas ride the generated model, so `models.py` must already be on disk — it is, checked in; a models drift is
    reported first."""
    reg = registry or Registry.shipped()
    root = out or GENERATED
    return {root / "models.py": render_models(reg), root / "tools.json": render_tools(reg)}


def write(registry: Registry | None = None, out: Path | None = None) -> list[Path]:
    """Two phases: the model first, then the tool schemas that ride it (the bootstrap of a fresh checkout)."""
    import importlib

    reg = registry or Registry.shipped()
    root = out or GENERATED
    root.mkdir(parents=True, exist_ok=True)
    models_path = root / "models.py"
    models_path.write_bytes(render_models(reg).encode("utf-8"))
    importlib.invalidate_caches()
    from .generated import models as models_mod

    importlib.reload(models_mod)
    tools_path = root / "tools.json"
    tools_path.write_bytes(render_tools(reg).encode("utf-8"))
    return [models_path, tools_path]


def drift(registry: Registry | None = None) -> list[Path]:
    """The paths whose checked-in bytes differ from what the schemas render — empty, or the build is out of date."""
    return [p for p, text in generate(registry).items() if not p.is_file() or p.read_bytes() != text.encode("utf-8")]


if __name__ == "__main__":  # `python -m isidium.store.registry.codegen`
    for p in write():
        print(p)
